runtime: nodejs14
env_variables:
  ACCESS_TOKEN_SECRET: 123
  GCLOUD_STORAGE_BUCKET: bucketproject3
  MONGODB_URL: mongodb+srv://cuopbien:123@shopping.nkk82.mongodb.net/bepmina?retryWrites=true&w=majority
  
